"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Post = { id: number; slug: string; title: string; excerpt: string; content: string; destination: string; duration: string; budget: string; season: string; category: string; color: string; status: string; featured: boolean };
type Lead = { id: number; name: string; email: string; destination: string; days: string; budget: string; note: string; source: string; status: string; createdAt: string };
type Data = { posts: Post[]; leads: Lead[]; settings: Record<string, string> };
const blank: Omit<Post, "id"> = { slug: "", title: "", excerpt: "", content: "", destination: "", duration: "", budget: "", season: "", category: "城市灵感", color: "forest", status: "draft", featured: false };

export function AdminDashboard({ userName, signOutUrl }: { userName: string; signOutUrl: string }) {
  const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState("overview"); const [editing, setEditing] = useState<Post | Omit<Post, "id"> | null>(null); const [toast, setToast] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/dashboard"); if (response.ok) setData(await response.json()); }, []);
  useEffect(() => { load(); }, [load]);
  const say = (text: string) => { setToast(text); setTimeout(() => setToast(""), 2200); };
  const savePost = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const hasId = "id" in editing; const response = await fetch(hasId ? `/api/admin/posts/${editing.id}` : "/api/admin/posts", { method: hasId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editing) }); if (response.ok) { setEditing(null); await load(); say("内容已保存"); } else say("保存失败，请检查字段"); };
  const removePost = async (id: number) => { if (!confirm("确定删除这篇内容？")) return; await fetch(`/api/admin/posts/${id}`, { method: "DELETE" }); await load(); say("内容已删除"); };
  const saveSettings = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await fetch("/api/admin/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); await load(); say("设置已更新"); };
  if (!data) return <main className="admin-loading">正在打开 Roam Insider 后台…</main>;
  const published = data.posts.filter((post) => post.status === "published").length;
  return <main className="admin-app">
    <aside className="admin-sidebar"><a className="admin-logo" href="/">ROAM<br />INSIDER</a><nav><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>⌂ 概览</button><button className={tab === "content" ? "active" : ""} onClick={() => setTab("content")}>✎ 内容</button><button className={tab === "leads" ? "active" : ""} onClick={() => setTab("leads")}>◎ 线索</button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}>⚙ 设置</button></nav><div className="admin-user"><span>{userName.slice(0, 1).toUpperCase()}</span><div><b>{userName}</b><a href={signOutUrl}>退出</a></div></div></aside>
    <section className="admin-main"><header><div><small>ROAM INSIDER / CONTROL ROOM</small><h1>{{ overview: "今天也离出发近一点。", content: "内容管理", leads: "潜在旅客", settings: "网站设置" }[tab]}</h1></div><a className="admin-preview" href="/" target="_blank">查看网站 ↗</a></header>
      {tab === "overview" && <><div className="stat-grid"><article><span>已发布路线</span><strong>{published}</strong><small>篇内容正在为你工作</small></article><article><span>累计线索</span><strong>{data.leads.length}</strong><small>路线咨询 + 邮件订阅</small></article><article><span>待处理</span><strong>{data.leads.filter((lead) => lead.status === "new").length}</strong><small>建议尽快回复</small></article></div><div className="admin-panel"><div className="panel-title"><h2>最近收到</h2><button onClick={() => setTab("leads")}>查看全部 →</button></div>{data.leads.slice(0, 5).map((lead) => <div className="mini-lead" key={lead.id}><span>{lead.name?.slice(0, 1) || "旅"}</span><div><b>{lead.name || lead.email}</b><small>{lead.destination || (lead.source === "newsletter" ? "邮件订阅" : "尚未决定目的地")}</small></div><time>{lead.createdAt.slice(0, 10)}</time></div>)}</div></>}
      {tab === "content" && <div className="admin-panel"><div className="panel-title"><div><h2>全部内容</h2><p>{data.posts.length} 篇路线与灵感</p></div><button className="admin-primary" onClick={() => setEditing({ ...blank })}>＋ 新建内容</button></div><div className="content-table">{data.posts.map((post) => <div className="content-row" key={post.id}><span className={`content-thumb ${post.color}`}>{post.destination.slice(0, 1)}</span><div><b>{post.title}</b><small>/{post.slug}</small></div><span className={`status ${post.status}`}>{post.status === "published" ? "已发布" : "草稿"}</span><button onClick={() => setEditing(post)}>编辑</button><button className="danger" onClick={() => removePost(post.id)}>删除</button></div>)}</div></div>}
      {tab === "leads" && <div className="admin-panel"><div className="panel-title"><div><h2>线索收件箱</h2><p>优先回复填写了旅行需求的人</p></div></div><div className="lead-table"><div className="lead-head"><span>联系人</span><span>想去哪里</span><span>时间 / 预算</span><span>来源</span><span>日期</span></div>{data.leads.map((lead) => <div className="lead-row" key={lead.id}><span><b>{lead.name || "邮件订阅者"}</b><small>{lead.email}</small></span><span>{lead.destination || "—"}<small>{lead.note || "暂无备注"}</small></span><span>{lead.days || "—"}<small>{lead.budget || "—"}</small></span><span>{lead.source}</span><span>{lead.createdAt.slice(0, 10)}</span></div>)}</div></div>}
      {tab === "settings" && <form className="admin-panel settings-form" onSubmit={saveSettings}><div className="panel-title"><div><h2>转化与公告</h2><p>更改后会立即影响前台</p></div></div><label>Trip 跳转链接<input name="trip_cta_url" defaultValue={data.settings.trip_cta_url} /></label><label>顶部公告<input name="site_announcement" defaultValue={data.settings.site_announcement} /></label><button className="admin-primary" type="submit">保存设置</button></form>}
    </section>
    {editing && <div className="editor-backdrop"><form className="editor" onSubmit={savePost}><header><div><small>EDITOR</small><h2>{"id" in editing ? "编辑内容" : "新建内容"}</h2></div><button type="button" onClick={() => setEditing(null)}>×</button></header><div className="editor-scroll"><label>标题<input value={editing.title} onChange={(e) => setEditing({ ...editing, title: e.target.value })} required /></label><div className="editor-two"><label>Slug<input value={editing.slug} onChange={(e) => setEditing({ ...editing, slug: e.target.value })} required /></label><label>目的地<input value={editing.destination} onChange={(e) => setEditing({ ...editing, destination: e.target.value })} /></label></div><label>摘要<textarea rows={3} value={editing.excerpt} onChange={(e) => setEditing({ ...editing, excerpt: e.target.value })} /></label><label>正文<textarea rows={12} value={editing.content} onChange={(e) => setEditing({ ...editing, content: e.target.value })} /></label><div className="editor-two"><label>天数<input value={editing.duration} onChange={(e) => setEditing({ ...editing, duration: e.target.value })} /></label><label>预算<input value={editing.budget} onChange={(e) => setEditing({ ...editing, budget: e.target.value })} /></label><label>季节<input value={editing.season} onChange={(e) => setEditing({ ...editing, season: e.target.value })} /></label><label>栏目<input value={editing.category} onChange={(e) => setEditing({ ...editing, category: e.target.value })} /></label><label>视觉色<select value={editing.color} onChange={(e) => setEditing({ ...editing, color: e.target.value })}><option value="forest">森林绿</option><option value="persimmon">柿子橙</option><option value="sky">天空蓝</option><option value="sage">鼠尾草</option></select></label><label>状态<select value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}><option value="draft">草稿</option><option value="published">发布</option></select></label></div><label className="check"><input type="checkbox" checked={editing.featured} onChange={(e) => setEditing({ ...editing, featured: e.target.checked })} /> 设为首页精选</label></div><footer><button type="button" onClick={() => setEditing(null)}>取消</button><button className="admin-primary" type="submit">保存内容</button></footer></form></div>}
    {toast && <div className="toast">{toast}</div>}
  </main>;
}
